openapi: 3.0.1
info:
  title: Cape Town Coffee Wiki Service
  description: This service provides information on coffee shops and there prices
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: Company
  - name: Products


paths:
  /v1/company/{name}:
    get:
      tags:
        - Company
      summary: Retrieve the coffee company details
      description: Retrieve coffee company details
      operationId: getCompanyName
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: the name of the company
        - in: header
          name: X-Correlation-Id
          schema:
            $ref: '#/components/schemas/UUIDv7'
          required: true
          description: Identifier to track API requests
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetCompanyNameResponseWrapper"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseWrapper"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseWrapper"
  /v1/company:
    get:
      tags:
        - Company
      summary: Retrieve all available coffee companies with their details
      description: Retrieve all available coffee companies with their details
      operationId: getAllCompanies
      parameters:
        - in: header
          name: X-Correlation-Id
          schema:
            $ref: '#/components/schemas/UUIDv7'
          required: true
          description: Identifier to track API requests
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAllCompaniesResponseWrapper"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseWrapper"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseWrapper"


  /v1/product/{companyCode}:
    get:
      tags:
        - Products
      summary: Retrieve products for a company
      description: Retrieve products for a specified company
      operationId: retrieveCpyProducts
      parameters:
        - in: path
          name: companyCode
          schema:
            type: string
          required: true
          description: the unique companyCode
        - in: query
          name: cursor
          schema:
            type: string
          required: false
          description: pagination cursor parameter
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
          description: pagination pageSize parameter
        - in: header
          name: X-Correlation-Id
          schema:
            $ref: '#/components/schemas/UUIDv7'
          required: true
          description: Identifier to track API requests

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetCpyProductResponseWrapper"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseWrapper"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseWrapper"

components:

  schemas:
    UUIDv7:
      type: string
      pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[7][0-9a-fA-F]{3}-[89aAbB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'


    GetCompanyNameResponseWrapper:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/Company"
        error:
          type: object
          nullable: true
          example: null

    GetAllCompaniesResponseWrapper:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Company"
        error:
          type: object
          nullable: true
          example: null



    GetCpyProductResponseWrapper:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/GetCpyProductResponse"
        error:
          type: object
          nullable: true
          example: null

    GetCpyProductResponse:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"
        nextCursor:
          type: string
          description: the next cursor to use
          example: x72ysS3cS9uUi5reeXgs7

    Company:
      type: object
      properties:
        code:
          type: string
          description: unique code asscociated to each company on creation
          example: 12weHIaq3ATOP1nM3Cx
        name:
          type: string
          description: the name of the company
          example: Starbucks

    Product:
      type: object
      required:
        - companyCode
        - name
        - variant
        - price
        - currency
      properties:
        companyCode:
          type: string
          description: unique code asscociated to each company on creation
          example: 12weHIaq3ATOP1nM3Cx
        code:
          type: string
          description: unique code asscociated to each product
          example: 12weHIaq3ATOP1nM3Cx
        name:
          type: string
          description: the name of the product
          example: Flat white
        variant:
          $ref: "#/components/schemas/ProductVariant"
        price:
          type: number
          format: decimal
          description: The price amount in the specified currency.
          example: 34.99
        currency:
          type: string
          description: The currency code (e.g., ZAR, USD).
          example: "ZAR"
        sequence:
          type: integer
          description: the product sequence as a guide as to where in a list it should be displayed
          example: 1

    ProductVariant:
      type: object
      properties:
        description:
          type: string
          description: describes the variant of the product
          example: "Small"
        sequence:
          type: integer
          description: the varaint sequence as a guide as to where in a list it should be displayed in relation to other variants of the same product
          example: 1

    ErrorResponseWrapper:
      type: object
      properties:
        data:
          type: object
          nullable: true
          example: null
        error:
          $ref: "#/components/schemas/ErrorResponse"

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: field describing the error
          example: No data available
        details:
          type: string
          description: details giving more information on the error
          example: No company data is available for the request